name: OpenCode Issue Assistant

on:
  issue_comment:
    types: [created]

jobs:
  opencode:
    if: contains(github.event.comment.body, '/oc') || contains(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT_TOKEN }} # чтобы коммиты шли от вашего имени

      - name: Configure git
        run: |
          git config --global user.email "vaceslavlebedev825@gmail.com"
          git config --global user.name "Slovuan-Swan"

      - name: Run OpenCode
        uses: anomalyco/opencode/github@dev
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          # Используем модель с высоким лимитом (1500 запросов/день)
          model: google/gemini-3-flash
          use_github_token: true
